/* 

* Operations can be used to run custom SQL that doesn't necessarily fit into the model of publishing a dataset or writing an assertion

* You can define multiple statements by separating them with a single line containing only 3 dashes ---

* resolve("table_name") returns the fully qualified name of the table

* Learn more on https://docs.dataform.co/guides/operations/

*/

-- The default file type is operation, so a config { } block is not required

CREATE TABLE ${resolve("dataform_test_table")} AS (SELECT 1 AS user_id)
--- 
DELETE FROM ${resolve("dataform_test_table")} WHERE user_id IS NULL 
---
DROP TABLE IF EXISTS ${resolve("dataform_test_table")}
