-- learn more on https://docs.dataform.co/guides/assertions/

config { 
    type: "assertion",
    tag: "advanced" 
}
with customers_table as (
    SELECT id as id, first_name as first_name, last_name as last_name, email as email, country as country
    FROM
        (SELECT '1' as id, 'Matt' as first_name, 'Smith' as last_name, 'matts@hotmail.tz' as email, 'UK' as country) UNION ALL
        -- (SELECT '1' as id, 'Matt' as first_name, 'Smith' as last_name, NULL as email, 'UK' as country) UNION ALL -- uncomment for assertion to fail
        (SELECT '2' as id, 'Julia' as first_name, 'Johnson' as last_name, 'jjohnson@company.net' as email, 'UK' as country) UNION ALL
        (SELECT '3' as id, 'John' as first_name, 'Williams' as last_name, 'jw@mail.ro' as email, 'FR' as country) UNION ALL
        (SELECT '4' as id, 'Patrick' as first_name, 'Jones' as last_name, 'pajones87@qq.co' as email, 'US' as country) UNION ALL
        (SELECT '5' as id, 'Alicia' as first_name, 'Brown' as last_name, 'alicia.brown@business.com' as email, 'US' as country) UNION ALL
        (SELECT '6' as id, 'Angelina' as first_name, 'Davis' as last_name, 'davis.angelina@gmail.zh' as email, 'US' as country) 
)

/* 
The following assertion checks the email field is always filled
*/

SELECT * FROM customers_table WHERE email IS NULL