/* files list


definitions/1_simple_examples/dataset_2_with_ref
definitions/1_simple_examples/dataset_1
definitions/2_advanced_examples/dataset_5_from_script_builder
definitions/2_advanced_examples/dataset_4_incremental_snapshot
definitions/2_advanced_examples/dataset_3_incremental_date
definitions/2_advanced_examples/generate_datasets_with_for_loop.js
definitions/3_operations_and_assertions/delete_deskop.ops
definitions/3_operations_and_assertions/simple_assertion.assert


includes/script_builder
includes/mapping
includes/generate_random_datasets
includes/utils

*/